# docker-compose.yml
services:
    postgres:
        image: postgres:15-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ponder
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
    anvil:
        build:
            context: .
            dockerfile: anvil.Dockerfile
        ports:
            - '8545:8545'
        healthcheck:
            test: >
                curl -X POST -H "Content-Type: application/json"
                --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
                http://localhost:8545
            interval: 5s
            timeout: 10s
            retries: 5

    ponder:
        build:
            context: .
            dockerfile: ponder/Dockerfile
        volumes:
            - .:/app
            - ponder-deps:/app/node_modules
            - ponder-app-deps:/app/ponder/node_modules
        ports:
            - '42069:42069'
        environment:
            - NODE_ENV=development
        depends_on:
            anvil:
                condition: service_healthy

    www:
        build:
            context: .
            dockerfile: www/Dockerfile
        volumes:
            - .:/app:delegated
            - www-deps:/app/node_modules
            - www-app-deps:/app/www/node_modules
        ports:
            - '3000:3000'
            - '3010:3010'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=200
        depends_on:
            - ponder
            
    dozzle:
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - '9999:8080'
        environment:
            DOZZLE_LEVEL: info
            DOZZLE_TAILSIZE: 300
            DOZZLE_FILTER: 'status=running'

volumes:
    postgres-data:
    ponder-deps:
    ponder-app-deps:
    www-deps:
    www-app-deps:
    www-vite:
