# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish pdk docker images

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./apps/wizard/
            dockerfile: ./apps/wizard/Dockerfile
            image: runiclabs/pdk-wizard
    steps:
      # include checkout step so we use path context rather than github context. Although working locally with docker buildx the
      # build-context in a parent directory doesn't seem to work with github context
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set commit hash
        id: set_commit_hash
        run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            ${{ github.ref == 'refs/heads/main' && format('type=raw,value={0}', env.hash) || '' }}

      - name: Build and push container image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: "${{matrix.context}}"
          file: "${{matrix.dockerfile}}"
          build-contexts: "root=./"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
